const {test}=require('node:test');const assert=require('node:assert/strict');
const {SyncController}=require('../controller.js');
const selection={projectKey:'project-1',clips:[{clipId:'a',name:'A',path:'/media/a.wav',startSample:'0'},{clipId:'b',name:'B',path:'/media/b.wav',startSample:'0'}]};
const session={address:'https://127.0.0.1:32145',sessionToken:'a'.repeat(64),protocolVersion:1};
const group={referenceClipId:'a',status:'matched',members:[{clipId:'a',offset:{ticks:'0',timebase:{numerator:1,denominator:8000}}},{clipId:'b',offset:{ticks:'500',timebase:{numerator:1,denominator:8000}}}],candidates:[{clipId:'b',status:'matched',reason:'AUDIO_MATCH',confidence:{score:1}}]};
const done={id:'job-1',kind:'sync',status:'completed',result:{sampleRate:8000,group}};
const deferred=()=>{let resolve;return {promise:new Promise(r=>resolve=r),resolve}};
function setup(overrides={},extra={}){const calls=[];const client={ping:async()=>({}),submit:async()=>{calls.push('submit');return {id:'job-1'}},getJob:async()=>done,cancel:async()=>{calls.push('cancel')},remove:async()=>{calls.push('remove')},...overrides};const controller=new SyncController({makeClient:()=>client,pollMs:0,isCurrent:async()=>true,...extra});return {controller,calls,client}}
async function ready(c){await c.connect(session);c.setSelection(selection,'a')}
test('does not enable analysis when authenticated handshake fails',async()=>{const {controller:c}=setup({ping:async()=>{throw Error('UNAUTHORIZED')}});await assert.rejects(()=>c.connect(session));assert.equal(c.state.phase,'disconnected');await assert.rejects(()=>c.run());});
test('submits once and exposes a report only after selection revalidation',async()=>{const {controller:c,calls}=setup();await ready(c);await c.run();assert.equal(c.state.phase,'completed');assert.equal(c.state.report.group.members[1].offset.ticks,'500');assert.deepEqual(calls,['submit','remove']);});
test('blocks double submission while the first POST is in flight',async()=>{const pending=deferred();const {controller:c,calls}=setup({submit:async()=>{calls.push('submit');return pending.promise}});await ready(c);const run=c.run();await new Promise(r=>setImmediate(r));await assert.rejects(()=>c.run(),/BUSY/);pending.resolve({id:'job-1'});await run;assert.equal(calls.filter(x=>x==='submit').length,1);});
test('cancellation during POST cancels the eventually returned job and suppresses results',async()=>{const pending=deferred();const {controller:c,calls}=setup({submit:()=>pending.promise});await ready(c);const run=c.run();await new Promise(r=>setImmediate(r));await c.cancel();pending.resolve({id:'job-1'});await run;assert.ok(calls.includes('cancel'));assert.equal(c.state.phase,'cancelled');assert.equal(c.state.report,null);});
test('keeps the job handle after a polling failure and retries status without resubmission',async()=>{let failed=true;const {controller:c,calls}=setup({getJob:async()=>{if(failed)throw Error('NETWORK');return done}});await ready(c);await assert.rejects(()=>c.run());assert.equal(c.state.phase,'unknown');await assert.rejects(()=>c.run(),/BUSY/);failed=false;await c.retryStatus();assert.equal(c.state.phase,'completed');assert.equal(calls.filter(x=>x==='submit').length,1);});
test('changing project during analysis marks the result stale',async()=>{let check=0;const {controller:c}=setup({}, {isCurrent:async()=>++check===1});await ready(c);await c.run();assert.equal(c.state.phase,'stale');assert.equal(c.state.report,null);});
test('clears the old report when the selection is changed',async()=>{const {controller:c}=setup();await ready(c);await c.run();c.setSelection({...selection,projectKey:'project-2'},'a');assert.equal(c.state.report,null);});
test('rejects malformed helper result instead of pretending it is usable',async()=>{const {controller:c}=setup({getJob:async()=>({...done,result:{group:{}}})});await ready(c);await assert.rejects(()=>c.run());assert.equal(c.state.report,null);});
test('selection arrays are copied before callers can mutate them',async()=>{const {controller:c}=setup();await c.connect(session);const s=JSON.parse(JSON.stringify(selection));c.setSelection(s,'a');s.clips[0].path='/changed.wav';assert.equal(c.selection.clips[0].path,'/media/a.wav');});
test('cancelling during final project check cannot publish a late completed report',async()=>{const pending=deferred();let checks=0;const {controller:c}=setup({}, {isCurrent:async()=>++checks===1?true:pending.promise});await ready(c);const run=c.run();while(checks<2)await new Promise(r=>setImmediate(r));await c.cancel();pending.resolve(true);await run;assert.equal(c.state.phase,'cancelled');assert.equal(c.state.report,null);});
test('export rejects a selection changed while its final check is in flight',async()=>{const pending=deferred();let delayed=false;const {controller:c}=setup({}, {isCurrent:async()=>delayed?pending.promise:true});await ready(c);await c.run();delayed=true;const report=c.reviewReport();c.setSelection({...selection,projectKey:'other'},'a');pending.resolve(true);await assert.rejects(()=>report,/SELECTION_CHANGED/);});
